### PR TITLE
feat(recipes): Add the FixJellyIssues recipe.

### PR DESCRIPTION
**Pull request by gounthar**
Adds XML declaration to Jelly files and create index.jelly if it doesn't exist thanks to the [addjellyxmldeclaration](https://docs.openrewrite.org/recipes/jenkins/addjellyxmldeclaration) and [createindexjelly](https://docs.openrewrite.org/recipes/jenkins/createindexjelly) recipes.

This is an attempt to solve #349.

## Walkthrough
The changes introduce a new recipe in the `recipes.yml` file for the Jenkins plugin modernizer, specifically `io.jenkins.tools.pluginmodernizer.FixJellyIssues`. This recipe ensures that the XML declaration `<?jelly escape-by-default='true'?>` is included in all `.jelly` files and creates an `index.jelly` file if it is absent. The recipe is categorized under 'chore' and includes references to two existing recipes for handling these tasks.

## Changes

| File Path                                           | Change Summary                                                                                   |
|-----------------------------------------------------|-------------------------------------------------------------------------------------------------|
| `plugin-modernizer-core/src/main/resources/META-INF/rewrite/recipes.yml` | Added a new recipe `io.jenkins.tools.pluginmodernizer.FixJellyIssues` to enforce XML declarations in `.jelly` files and create `index.jelly` files. |

### Submitter checklist
- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by gounthar** [comment]
The recipe supposed to fix the missing `XML` declaration has been [released](https://github.com/openrewrite/rewrite-jenkins/releases/tag/v0.17.0), but it looks like it's doing nothing. 😢 
```
java -jar plugin-modernizer-cli/target/jenkins-plugin-modernizer-999999-SNAPSHOT.jar --plugins BlazeMeterJenkinsPlugin --recipes FixJellyIssues --skip-pull-request --skip-build
Starting Plugin Modernizer
Forking plugin BlazeMeterJenkinsPlugin locally from repo blazemeter-plugin...
Synced the forked repository for plugin BlazeMeterJenkinsPlugin
Fetching plugin code locally BlazeMeterJenkinsPlugin...
Fetched repository from https://github.com/gounthar/blazemeter-plugin.git to branch refs/heads/master
Collecting metadata for plugin BlazeMeterJenkinsPlugin... Please be patient
Done
Running recipes io.jenkins.tools.pluginmodernizer.FixJellyIssues for plugin BlazeMeterJenkinsPlugin... Please be patient
Done
No JDKs found in metadata for plugin BlazeMeterJenkinsPlugin. Using same JDK as rewrite for verification
Skipping formatting for plugin BlazeMeterJenkinsPlugin as it is not using Spotless
Skipping verification for plugin BlazeMeterJenkinsPlugin
Plugin BlazeMeterJenkinsPlugin verified successfully with JDK 17
Collecting metadata for plugin BlazeMeterJenkinsPlugin... Please be patient
Done
No commits to push for plugin BlazeMeterJenkinsPlugin
Skipping pull request for plugin BlazeMeterJenkinsPlugin
*************
Plugin: BlazeMeterJenkinsPlugin
Skip pull request mode. Changes were pushed on https://github.com/gounthar/blazemeter-plugin but no pull request was open on https://github.com/jenkinsci/blazemeter-plugin
*************
Plugin Modernizer finished.
```
and
```
~/.cache/jenkins-plugin-modernizer-cli/BlazeMeterJenkinsPlugin/sources (plugin-modernizer-tool)$ head ./src/main/resources/hudson/plugins/blazemeter/PerformanceBuilder/global.jelly
<j:jelly xmlns:j="jelly:core"
         xmlns:st="jelly:stapler"
         xmlns:d="jelly:define"
         xmlns:l="/lib/layout"
         xmlns:t="/lib/hudson"
         xmlns:f="/lib/form">
    <!--
 Copyright 2018 BlazeMeter Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
```
Even the [recipe itself](https://docs.openrewrite.org/recipes/jenkins/addjellyxmldeclaration) outside of plugin-modernizer does nothing:
`mvn -U org.openrewrite.maven:rewrite-maven-plugin:run -Drewrite.recipeArtifactCoordinates=org.openrewrite.recipe:rewrite-jenkins:RELEASE -Drewrite.activeRecipes=org.openrewrite.jenkins.AddJellyXmlDeclaration -Drewrite.exportDatatables=true`
and
```
~/.cache/jenkins-plugin-modernizer-cli/BlazeMeterJenkinsPlugin/sources (plugin-modernizer-tool)$ head ./src/main/resources/hudson/plugins/blazemeter/PerformanceBuilder/global.jelly
<j:jelly xmlns:j="jelly:core"
         xmlns:st="jelly:stapler"
         xmlns:d="jelly:define"
         xmlns:l="/lib/layout"
         xmlns:t="/lib/hudson"
         xmlns:f="/lib/form">
    <!--
 Copyright 2018 BlazeMeter Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
```

Still no `<?jelly escape-by-default`...

**Comment by jonesbusy** [comment]
@gounthar I think it's because of the *.jelly files are quarks (not idenfied as files)

We need to thread them as text file I think

https://github.com/openrewrite/rewrite-maven-plugin/blob/3dcec7f65e46c6740ca32f4dfd24e2d8d511a914/src/main/java/org/openrewrite/maven/ConfigurableRewriteMojo.java#L118

Can you try via maven plugin directly using `-Drewrite.additionalPlainTextMasks=**/*.jelly' ?

If yes we can add this CLI argument on plugin modernizer

**Comment by gounthar** [comment]
Thanks, Valentin, let me try that. 👍

**Comment by jonesbusy** [comment]
Or perhaps even added on https://github.com/openrewrite/rewrite-maven-plugin/blob/3dcec7f65e46c6740ca32f4dfd24e2d8d511a914/src/main/java/org/openrewrite/maven/ConfigurableRewriteMojo.java#L127

I see svg files are also added as text file. Not XML. So would make sense to have *.jelly files as text by default

**Comment by gounthar** [comment]
Okay, the new command line parameter did the trick with the recipe:
`mvn -U org.openrewrite.maven:rewrite-maven-plugin:run -Drewrite.recipeArtifactCoordinates=org.openrewrite.recipe:rewrite-jenkins:RELEASE -Drewrite.activeRecipes=org.openrewrite.jenkins.AddJellyXmlDeclaration -Drewrite.exportDatatables=true -Drewrite.additionalPlainTextMasks=**/*.jelly`
gave
```
@@ -1,3 +1,4 @@
+<?jelly escape-by-default='true'?>
 <j:jelly xmlns:j="jelly:core"
          xmlns:st="jelly:stapler"
          xmlns:d="jelly:define"
diff --git a/src/main/resources/hudson/plugins/blazemeter/PerformanceReportMap/index.jelly b/src/main/resources/hudson/plugins/blazemeter/PerformanceReportMap/index.jelly
index e9c3040..29b598c 100644
--- a/src/main/resources/hudson/plugins/blazemeter/PerformanceReportMap/index.jelly
+++ b/src/main/resources/hudson/plugins/blazemeter/PerformanceReportMap/index.jelly
@@ -1,3 +1,4 @@
+<?jelly escape-by-default='true'?>
 <j:jelly xmlns:j="jelly:core" xmlns:st="jelly:stapler" xmlns:d="jelly:define"
          xmlns:l="/lib/layout" xmlns:t="/lib/hudson" xmlns:f="/lib/form">
     <!--
diff --git a/src/main/resources/index.jelly b/src/main/resources/index.jelly
index 5c942f0..d127448 100644
--- a/src/main/resources/index.jelly
+++ b/src/main/resources/index.jelly
@@ -1,3 +1,4 @@
+<?jelly escape-by-default='true'?>
 <!--
  Copyright 2018 BlazeMeter Inc.
```

I will create a new PR on OpenRewrite.

**Comment by gounthar** [comment]
My [PR](https://github.com/openrewrite/rewrite-maven-plugin/pull/897) has been merged, but no version has been released yet.

**Comment by gounthar** [comment]
My [PR](https://github.com/openrewrite/rewrite-maven-plugin/releases/tag/v5.46.0) has been merged, let's retry it!

**Comment by gounthar** [comment]
And it worked! 🚀 
https://github.com/jenkinsci/blazemeter-plugin/compare/master...gounthar:blazemeter-plugin:plugin-modernizer-tool

**Review by jonesbusy — APPROVED** [review]

**Pull request merged**
