### PR TITLE
chore(ga): Fix Docker build and integrate into release process

### LINKED ISSUE #502: Docker build broken and main and switch to docker build when release
### What feature do you want to see added?

Both bug and enhancement

Historically the docker build was done on main

Now that we have a release process in place (with homebrew distribution) it would be great if we can fix and change the docker build into the release process instead of a moving main tag

### Upstream changes

Also understand why docker build is failing

Screenshot from 2024-12-23 09-14-19

### Are you interested in contributing this feature?

_No response_

### PR DESCRIPTION
**Pull request by gounthar**
Fixes #502 .

Integrate Docker build process into the release workflow.

* **.github/workflows/cd.yaml**
  - Add a new job to build and push Docker image using `docker/build-push-action`.
  - Ensure Docker image is tagged with the release version.

* **.github/workflows/github-docker-registry-push.yml**
  - Delete the file to remove the Docker build process from the `main` branch.

- **CI/CD Updates**
	- Enhanced GitHub Actions workflow to support Docker image builds and pushes.
	- Removed previous Docker registry push workflow.
	- Updated Dockerfile to improve version management and build process.

- **Infrastructure**
	- Streamlined Docker image creation and deployment configuration.

### Testing done
```
gh act -j release
INFO[0000] Using docker host 'unix:///var/run/docker.sock', and daemon socket 'unix:///var/run/docker.sock' 
[cd/validate] 🚀  Start image=node:16-buster-slim
[cd/validate]   🐳  docker pull image=node:16-buster-slim platform= username= forcePull=true
[cd/validate]   🐳  docker create image=node:16-buster-slim platform= entrypoint=["tail" "-f" "/dev/null"] cmd=[] network="host"
[cd/validate]   🐳  docker run image=node:16-buster-slim platform= entrypoint=["tail" "-f" "/dev/null"] cmd=[] network="host"
[cd/validate]   🐳  docker exec cmd=[node --no-warnings -e console.log(process.execPath)] user= workdir=
[cd/validate]   ☁  git clone 'https://github.com/jenkins-infra/verify-ci-status-action' # ref=v1.2.2
[cd/validate] ⭐ Run Pre Verify CI status
[cd/validate]   ✅  Success - Pre Verify CI status
[cd/validate]   ☁  git clone 'https://github.com/release-drafter/release-drafter' # ref=3f0f87098bd6b5c5b9a36d49c41d998ea58f9348
[cd/validate]   ☁  git clone 'https://github.com/jenkins-infra/interesting-category-action' # ref=v1.2.1
[cd/validate] ⭐ Run Pre Check interesting categories
[cd/validate]   ✅  Success - Pre Check interesting categories
[cd/validate] ⭐ Run Main Verify CI status
[cd/validate]   🐳  docker cp src=/home/gounthar/.cache/act/jenkins-infra-verify-ci-status-action@v1.2.2/ dst=/var/run/act/actions/jenkins-infra-verify-ci-status-action@v1.2.2/
[cd/validate] ⭐ Run Main $GITHUB_ACTION_PATH/run.sh
[cd/validate]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/verify-ci-status-composite-verify-ci-status.sh] user= workdir=
| unknown-event-type-push
[cd/validate]   ✅  Success - Main $GITHUB_ACTION_PATH/run.sh
[cd/validate]   ⚙  ::set-output:: result=unknown-event-type-push
[cd/validate]   ⚙  ::set-output:: result=unknown-event-type-push
[cd/validate]   ✅  Success - Main Verify CI status
[cd/validate]   ⚙  ::set-output:: result=unknown-event-type-push
[cd/validate] ⭐ Run Post Verify CI status
[cd/validate]   🐳  docker cp src=/home/gounthar/.cache/act/jenkins-infra-verify-ci-status-action@v1.2.2/ dst=/var/run/act/actions/jenkins-infra-verify-ci-status-action@v1.2.2/
[cd/validate]   ✅  Success - Post Verify CI status
[cd/validate] Cleaning up container for job validate
[cd/validate] 🏁  Job succeeded
```
### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Review by jonesbusy — COMMENTED** [review]
I think we cannot just do anymore a mvn clean install on the Dockerfile. Because it will create a build with wrong version.

We need either to pass the set.changelist or copy the previously built jar (it's probably the best I think)

**Review by jonesbusy — APPROVED** [review]

**Comment by jonesbusy** [comment]
Thanks! We can give it a shot today (I'm planning to push a release)

**Comment by jonesbusy** [comment]
Sadly it fail https://github.com/jenkins-infra/plugin-modernizer-tool/actions/runs/12544941525/job/34978434540

**Comment by gounthar** [comment]
because of a permission problem...
I will try to find the differences between the previous GitHub Action and `cd`.
I think the previous action was working with the default credentials, and this one works with your GitHub handle.

**Comment by jonesbusy** [comment]
```yaml
permissions:
  checks: read
  contents: write
```

Missing `packages: write` ?

**Comment by gounthar** [comment]
That could also help, yes.

**Pull request merged**
