### PR TITLE
Add CLI Integration Test and Refine Maven Configuration

### PR DESCRIPTION
**Pull request by SohamJuneja**
Added a new CLI integration test to validate functionality.
Updated exec-maven-plugin configuration to directly run the CLI JAR (target/cli.jar).

### CODE REVIEW

**Comment by krisstern** [comment]
Hi @SohamJuneja it appears you have a NullPointerException in your code.

This is what I see in the logs:
```console
java.lang.NullPointerException
	at java.base/java.io.File.<init>(File.java:278)
	at ch.qos.logback.core@1.5.12/io.jenkins.tools.pluginmodernizer.cli.MavenInvokerIT.runIntegrationTest(MavenInvokerIT.java:27)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
```

**Comment by SohamJuneja** [comment]
@krisstern yup , thanks . Don't know how it worked on my local system. I've figured out that MAVEN_HOME environment variable is not set or empty . As it is on line 27 . Further deep checking revealed that getDefaultMavenHome() function returns NULL if both MAVEN_HOME and M2_HOME are not set .

**Comment by jonesbusy** [comment]
Surefire is using

```xml
<configuration>
  <environmentVariables>
    <MAVEN_HOME>${project.build.directory}/apache-maven-${maven.version}</MAVEN_HOME>
  </environmentVariables>
</configuration>
```

to have a predictable maven version and not be dependent from the environment

For failsafe it might be different. You need to find a way to pass this to the subprocess

**Comment by jonesbusy** [comment]
Please also avoid opening a PR from the `main` branch of your fork but by creating feature branch.

**Comment by SohamJuneja** [comment]
@jonesbusy Locally, I’m able to run mvn clean test successfully, but mvn clean install fails with the same exit code 1 during the integration test execution. To capture more details, I've handled different exceptions locally and printed the output, but the issue persists.
[ERROR]   MavenInvokerIT.runIntegrationTest:57 IllegalState Build failed with exit code: 1
I've tried multiple things including adding the environment variables in the failsafe plugin and also modified the maven.config file, but I'm still encountering the same error during the integration test.
Will keep in mind the PR thing , apologies.

**Comment by jonesbusy** [comment]
Perhaps we should have a different module running the integration tests ? I did some tests here https://github.com/jenkins-infra/plugin-modernizer-tool/pull/456

**Comment by SohamJuneja** [comment]
Yes, maybe that would be better. I’ve already spent a great amount of time trying to figure out a solution this way, but it didn’t yield much benefit. While creating a separate module would make the issue more complex in my opinion, I agree that it might be a better approach.

**Comment by jonesbusy** [comment]
Thanks for your effort. I have a working PR here https://github.com/jenkins-infra/plugin-modernizer-tool/pull/457

Feel free to submit an other PR to complete tests or improve it

**Pull request closed without merging**
